### PR TITLE
Migrating Tutorials to the new theme

### PR DESCRIPTION
**Pull request by tarzzz**
- Added 3D Surface Plot

### CODE REVIEW

**Comment by tarzzz** [comment]
@NicoleGrondin I see you have a version of 3D surface plot in master. 
This one is as per the new theme, as well uses plotly CDN for image hosting (images.plot.ly). 
Should I merge this one as well in master,

**Comment by NicoleGrondin** [comment]
@tarzzz if you have a newer version of that tutorial, could your remove the old one in this commit? No point in having two 3D surface plot tutorials.

**Comment by tarzzz** [comment]
Sure, will do. Thanks

**Comment by tarzzz** [comment]
Done, Merging in.

**Pull request merged**
