### PR TITLE
Replace hero background 

### PR DESCRIPTION
**Pull request by jdamiba**
closes https://github.com/plotly/plotly.github.io/issues/501
Screen Shot 2019-08-13 at 2 32 37 PM

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
Reminder: https://github.com/plotly/plotly.github.io/issues/501#issuecomment-516656941 ... please use logo *without* "Graphing Libraries" ... just a plain Plotly logo

**Comment by jdamiba** [comment]
This PR has been updated to use a different logo. 

Screen Shot 2019-08-13 at 4 10 53 PM

**Comment by jdamiba** [comment]
@michaelbabyn This PR has been updated with a commit to add the Asap Google Font to the `<head>` of the index in order to ensure that the font renders. 

Screen Shot 2019-08-14 at 10 44 46 AM

**Comment by jdamiba** [comment]
Thanks for catching that @michaelbabyn. I pushed a commit to style the `demo dash button`. I removed the mobile nav to sync with the `documentation` repo in advance of my PRs later this week to update the desktop and mobile nav menus with the marketing site. 

Screen Shot 2019-08-14 at 12 51 20 PM

**Comment by nicolaskruchten** [comment]
Is there an issue re mobile nav on this site and the doc site? I removed the mobile nav on the doc site and it was not my intention to restore it.

**Comment by jdamiba** [comment]
My understanding from https://github.com/plotly/plotly.github.io/issues/501#issuecomment-519955023 was that the nav menu on `plot.ly/api` and `help.plot.ly` should mirror that of `plot.ly` in its entirety. I created https://github.com/plotly/plotly.github.io/issues/507 and https://github.com/plotly/documentation/issues/1456 to track that work. 

However, your previous comment in this thread makes it sound like you only want the full size navigation menu on `plot.ly/api` and `help.plot.ly`? Can you confirm that I should not implement a mobile nav menu on `plot.ly/api` and `help.plot.ly`?

**Comment by nicolaskruchten** [comment]
Correct: no mobile nav. #501 says nothing about mobile nav actually. It says to roll out the simple logo/demo-dash nav to the whole help.plot.ly site. 

In mobile mode you can do the same thing as in the doc site and hide the demo-dash button leaving only the logo.

**Comment by jdamiba** [comment]
Ok, in that case this @michaelbabyn this PR is good to go- the mobile behavior is as @nicolaskruchten describes in his comment above- the `demo dash` button disappears leaving only the logo, same as what happens in `documentation`.

**Pull request merged**
