### PR TITLE
Remove marketing links

### PR DESCRIPTION
**Pull request by jdamiba**
closes https://github.com/plotly/plotly.github.io/issues/390

### CODE REVIEW

**Comment by nicolaskruchten** [comment]
is that Data Integrations page really not needed? @cldougl confirm plz?

**Comment by jdamiba** [comment]
The actual `getting-data` page is at https://help.plot.ly/getting-data/.

screen shot 2018-10-15 at 3 04 19 pm


The page I removed is being served from https://help.plot.ly/static/images/getting-data/Data%20integrations.html within the `/static/images/` folder, which I do not believe is intended behavior since it is the only such `html`in that folder and has very off-brand styling. 
screen shot 2018-10-15 at 3 04 29 pm

**Comment by cldougl** [comment]
yeah we definitely don't want that file anymore but it looks like that url is showing up when searching so we should add a redirect in the getting-data tutorial just to be safe. 
screen shot 2018-10-24 at 11 51 16 am

**Comment by nicolaskruchten** [comment]
💃 to the marketing link change but let's drop the dead code commit for now and get that into a separate PR

**Comment by nicolaskruchten** [comment]
let's merge this!

**Pull request merged**
