### PR TITLE
Ben edits

### PR DESCRIPTION
**Pull request by mariahhamel**
tutorial edits

still need to add thumbnails, put pictures on github (they're on imgur)

### CODE REVIEW

**Comment by mariahhamel** [comment]
@chriddyp Do you have time to check this out? I'm not sure why it can't merge.

**Comment by mariahhamel** [comment]
@mkcor Can you look into this when you have a chance?

**Comment by mkcor** [comment]
@mariahhamel On it.

We can't merge directly because `master` is ahead and has, for example,
```
permalink: /how-to-label-points-with-text-in-a-scatter-plot-online
```
where this branch says
```
permalink: /label-points-with-text-in-a-scatter-plot
```
so Git doesn't know which version it should go for...

I'll resolve the conflicts manually (for reference, see https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/).

**Comment by mkcor** [comment]
Okay, we could merge now, but I don't find this tutorial readable at all.

Like...

readability

Screenshots are cropped in such a way that they're super confusing. And this text around pictures... It looks like the sentence is not ending...

And what's with the '|'?

I believe @MatthewHiscock could fix these, his submissions have been very clean.

**Comment by mariahhamel** [comment]
Thanks @mkcor ! 

I quickly edited these for Ben, but didn't have time to redo screen shots. I think the | only shows up in the preview, and puts the tutorial into a table via markdown.

**Comment by mkcor** [comment]
@mariahhamel Okay. Feel free to merge then. We'll iterate, as usual. :baby_chick:

**Comment by mariahhamel** [comment]
I just fixed a couple typos (double image, and a broken image). 

Text isn't around pictures (I don't think), it just falls to the next line, which is lined up with the image in preview mode:

screen shot 2015-06-16 at 2 58 51 pm

**Pull request merged**
