### PR TITLE
Bar Charts Doc update

### PR DESCRIPTION
**Pull request by priyatharsan**
related to https://github.com/plotly/plotly.github.io/issues/372
Doc update for:
- [x] Grouped Bar Charts
- [x] Stacked Bar Charts
- [x] Horizontal Bar Charts

### CODE REVIEW

**Comment by cldougl** [comment]
cc @@ashmpace for a quick spelling/grammar review

**Comment by ashmpace** [comment]
Proofed and made small copy edits. Good by me 👍

**Comment by cldougl** [comment]
I think this chart looks great! 
Would you be able to find a different dataset? I think it is a bit weird to have a dataset about color but different colors used in the chart:


screen shot 2018-10-15 at 10 30 14 am

**Comment by cldougl** [comment]
screen shot 2018-10-15 at 10 31 48 am

can you use more contrasting colors here-- it's a bit hard to read this chart 👓

**Comment by priyatharsan** [comment]
@cldougl the requested style changes are done. This PR is ready for review.

**Pull request merged**
