### PR TITLE
update images in how to signup page

### PR DESCRIPTION
**Pull request by priyatharsan**
related to https://github.com/plotly/plotly.github.io/issues/408

### CODE REVIEW

**Comment by cldougl** [comment]
@priyatharsan is this still wip or is this ready for review?

**Comment by priyatharsan** [comment]
this is still in WIP, I will take a look today.

**Comment by cldougl** [comment]
@priyatharsan do you think it would be possible for you to reopen this PR cleanly? There's 89 commits in it now so it's quite hard to review/see what the intentional changes were.

**Comment by priyatharsan** [comment]
yep! I will create a new PR

**Pull request closed without merging**
